
<h1>PowerTools</h1>
<p>Magento2 playground</p>
<?php
// Test your classes and methods
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cms = $objectManager->create(Syncit\PowerTools\Block\Categories::class);
$page = $objectManager->create(Syncit\PowerTools\Block\CurrentPage::class);
$browser = $objectManager->create(Syncit\PowerTools\Block\Browser::class);
$attr = $objectManager->create(Syncit\PowerTools\Block\Attributes::class);
//$page->dumpCurrentPage();
//echo $page->getCurrentPageId();
//$cms->dumpAllCategories();
// Example get browser, version, and platform
// echo $browser->getBrowser()." ". $browser->getVersion() ."<br/>";
// echo $browser->getPlatform();
?>
<?php // Get all products using coollection or repository ?>
<?php  //$productsRepository = $this->getProductData();?> 
<?php  //$productsCollection = $this->getProducts();?>
<?php  $attr->getAllAttributesNames()?>
